import asyncio
import json
import logging
import os
import random
import re
import shutil
import sys
import time
from dataclasses import dataclass, asdict
from typing import Optional

from bot.models.dialects import Dialect

logger = logging.getLogger(__name__)


@dataclass
class Quiz:
    """Structured quiz generated by AI."""
    id: int
    question: str
    options: list[str]
    correct_index: int
    category: str = ""
    ru_title: str = ""  # Traducción al ruso del título (solo quizzes en español, niveles A1-B1)
    lang: str = ""  # "es" / "ru" — asignado tras el parseo para identificar el idioma

    @property
    def correct_option(self) -> str:
        return self.options[self.correct_index]

    def to_dict(self) -> dict:
        return asdict(self)

    def shuffle_options(self) -> None:
        """Randomize option order and update correct_index to track the correct answer."""
        paired = list(zip(self.options, range(len(self.options))))
        random.shuffle(paired)
        self.options = [p[0] for p in paired]
        self.correct_index = next(i for i, (_, orig) in enumerate(paired) if orig == self.correct_index)

    @classmethod
    def from_dict(cls, data: dict) -> "Quiz":
        correct = data.get("correct", data.get("correct_index", 0))
        quiz = cls(
            id=int(data.get("id", 0)),
            question=str(data["question"]).strip(),
            options=[str(o).strip() for o in data["options"]],
            correct_index=int(correct),
            category=str(data.get("category", "")),
            ru_title=str(data.get("ru_title", "") or "").strip(),
            lang=str(data.get("lang", "") or "").strip(),
        )
        quiz.shuffle_options()
        return quiz


@dataclass
class AutoDetected:
    """Auto-detected settings from a forwarded message."""
    topic: str
    examples: list[str]
    level: str  # A1-C2
    dialect: str  # Castellano, Mexicano, Caribeño, Rioplatense, Chileno


class AIServiceError(Exception):
    def __init__(self, message: str, category: str = "EXTERNAL", status_code: int = 500):
        super().__init__(message)
        self.category = category
        self.status_code = status_code


class AIService:
    def __init__(self):
        self.timeout = 300.0  # 5 minutes — covers generate + review + fix stages
        self.max_retries = 2
        self.base_delay = 1.0

    # ── public ──────────────────────────────────────────────

    async def generate_quizzes(
        self, topic: str, count_es: dict[str, int], count_ru: dict[str, int],
        level: str, dialect: str, examples: list[str] | None = None,
        forwarded_posts: list[str] | None = None,
    ) -> list[Quiz]:
        """
        Generate quizzes with per-category counts.
        count_es = {"fill_blank": 2, "meaning": 1, "synonyms": 0, "slang": 1}
        count_ru = {"fill_blank": 1, "meaning": 2, "synonyms": 1, "slang": 0}
        examples = optional list of example sentences from the original post
        forwarded_posts = optional list of forwarded post texts (for multi-post workflow)
        """
        total_es = sum(count_es.values())
        total_ru = sum(count_ru.values())

        logger.info("Generating %d quizzes — topic='%s', level=%s, dialect=%s",
                     total_es + total_ru, topic, level, dialect)

        user = self._build_generate_user_prompt(topic, count_es, count_ru, level, dialect, examples, forwarded_posts)

        raw = await self._call_api_with_retry(user)
        result = self._try_parse_structured_response(raw)

        if result is None:
            logger.warning("AI returned unparseable response, requesting reformat")
            fix_prompt = (
                "Tu respuesta anterior no era JSON válido. "
                "Aquí está tu respuesta:\n\n"
                f"{raw}\n\n"
                "Por favor, reformátala EXACTAMENTE así, sin texto adicional, sin markdown, sin ```:\n"
                '{"espanol":[{"id":1,"category":"fill_blank","question":"...","options":["A","B","C","D"],"correct":0,'
                '"ru_title":"..."}],'
                '"ruso":[{"id":1,"category":"meaning","question":"...","options":["A","B","C","D"],"correct":0}]}\n'
                "Nota: 'ru_title' (traducción al ruso de la pregunta) SOLO aplica a los quizzes de 'espanol'."
            )
            raw2 = await self._call_api_with_fix_prompt(user, fix_prompt)
            result = self._try_parse_structured_response(raw2)

            if result is None:
                raise AIServiceError(
                    "La IA no pudo generar quizzes con formato válido. Intenta de nuevo.",
                    category="PARSE_ERROR",
                    status_code=502,
                )

        espanol_quizzes = result.get("espanol", [])
        ruso_quizzes = result.get("ruso", [])

        # Enforce totals
        espanol_quizzes = espanol_quizzes[:total_es]
        ruso_quizzes = ruso_quizzes[:total_ru]

        # Marcar idioma — sobrevive los to/from_dict del almacenamiento FSM
        for q in espanol_quizzes:
            q.lang = "es"
        for q in ruso_quizzes:
            q.lang = "ru"

        # Assign sequential ids
        all_quizzes = espanol_quizzes + ruso_quizzes
        for i, q in enumerate(all_quizzes):
            q.id = i + 1

        logger.info("Generated %d quizzes (%d es + %d ru)", len(all_quizzes), len(espanol_quizzes), len(ruso_quizzes))
        return all_quizzes

    async def determine_topic(self, text: str, is_multi_post: bool = False) -> AutoDetected:
        """Extract topic, examples, level, and dialect from a forwarded message or multiple posts."""
        multi_post_context = ""
        if is_multi_post:
            multi_post_context = (
                "\n\nCONTEXTO IMPORTANTE: Estos posts son parte de un quiz SEMANAL.\n"
                "El usuario reenvió múltiples posts de canales de español para crear un quiz.\n"
                "Determina un tema que unifique TODOS los posts.\n"
            )

        user = self._build_topic_user_prompt(text, is_multi_post, multi_post_context)
        raw = await self._call_api_with_retry(user)

        # Parse JSON
        cleaned = re.sub(r"```(?:json)?\s*", "", raw).strip().rstrip("`")
        try:
            data = json.loads(cleaned)
            return self._parse_auto_detected(data)
        except (json.JSONDecodeError, KeyError, ValueError, TypeError):
            pass

        # Try regex fallback
        match = re.search(r"\{.*\}", raw, re.DOTALL)
        if match:
            try:
                data = json.loads(match.group())
                return self._parse_auto_detected(data)
            except (json.JSONDecodeError, KeyError, ValueError, TypeError):
                pass

        # Last resort
        return AutoDetected(topic="NO_TOPIC", examples=[], level="A1", dialect="Castellano")

    def _parse_auto_detected(self, data: dict) -> AutoDetected:
        topic = str(data.get("topic", "NO_TOPIC")).strip()
        examples = [str(e).strip() for e in data.get("examples", []) if isinstance(e, str)]
        level = str(data.get("level", "A1")).strip().upper()
        dialect = Dialect.from_name(str(data.get("dialect", "Castellano"))).display_name

        # Validate level
        if level not in ("A1", "A2", "B1", "B2", "C1", "C2"):
            level = "A1"

        return AutoDetected(topic=topic, examples=examples, level=level, dialect=dialect)

    async def determine_category_counts(
        self, topic: str, examples: list[str],
        count_es: dict[str, int], count_ru: dict[str, int],
        level: str, dialect: str,
    ) -> tuple[dict[str, int], dict[str, int]]:
        """
        Analyze the topic and examples to suggest category counts per language.
        Returns (counts_es, counts_ru) with values 0+ per category.
        The AI decides what makes sense given the content.
        """
        user = self._build_category_counts_user_prompt(topic, examples, count_es, count_ru, level, dialect)
        raw = await self._call_api_with_retry(user)

        # Parse JSON
        cleaned = re.sub(r"```(?:json)?\s*", "", raw).strip().rstrip("`")
        try:
            data = json.loads(cleaned)
            return self._parse_category_counts(data, count_es, count_ru)
        except (json.JSONDecodeError, KeyError, ValueError, TypeError):
            pass

        match = re.search(r"\{.*\}", raw, re.DOTALL)
        if match:
            try:
                data = json.loads(match.group())
                return self._parse_category_counts(data, count_es, count_ru)
            except (json.JSONDecodeError, KeyError, ValueError, TypeError):
                pass

        # Fallback: return original counts unchanged
        return count_es, count_ru

    @staticmethod
    def _parse_category_counts(
        data: dict, default_es: dict[str, int], default_ru: dict[str, int]
    ) -> tuple[dict[str, int], dict[str, int]]:
        raw_es = data.get("espanol", {})
        raw_ru = data.get("ruso", {})

        def _valid(raw: dict, defaults: dict[str, int]) -> dict[str, int]:
            out = {}
            for key in defaults:
                val = raw.get(key, defaults[key])
                val = max(0, int(val))  # no upper cap
                out[key] = val
            if sum(out.values()) < 1:
                # Ensure at least 1 total — set first category to 1
                first_key = list(out.keys())[0]
                out[first_key] = 1
            return out

        return _valid(raw_es, default_es), _valid(raw_ru, default_ru)

    async def review_quizzes(
        self, quizzes: list[Quiz], topic: str, level: str, dialect: str,
    ) -> list[dict]:
        """
        Review all quizzes for technical issues.
        Returns a list of issues: [{"id": 3, "issue": "...", "fix": {...}}, ...]
        Empty list = no issues found.
        """
        logger.info("Reviewing %d quizzes for issues", len(quizzes))
        quizzes_data = [q.to_dict() for q in quizzes]
        user = self._build_review_user_prompt(quizzes_data, topic, level, dialect)

        raw = await self._call_api_with_retry(user, agent="quiz-reviewer")

        # Parse JSON
        cleaned = re.sub(r"```(?:json)?\s*", "", raw).strip().rstrip("`")
        issues: list[dict] = []
        try:
            data = json.loads(cleaned)
            issues = data.get("issues", [])
        except (json.JSONDecodeError, KeyError, ValueError, TypeError):
            pass

        if not issues:
            match = re.search(r"\{.*\}", raw, re.DOTALL)
            if match:
                try:
                    data = json.loads(match.group())
                    issues = data.get("issues", [])
                except (json.JSONDecodeError, KeyError, ValueError, TypeError):
                    pass

        if not issues:
            # If we can't parse the review, return empty (no issues) — don't block publishing
            if not issues and not data:
                logger.warning("AI review returned unparseable response, skipping review")
            else:
                logger.info("Review found 0 issues")
            return []

        logger.info("Review found %d issue(s): %s", len(issues),
                     ", ".join(f"#{i.get('id')}: {i.get('issue', '?')}" for i in issues))
        return issues

    async def edit_quiz(
        self, topic: str, history: list[dict], quiz_id: int, feedback: str
    ) -> Quiz:
        """Edit a single quiz (PATCH style). Returns only the modified quiz."""
        logger.info("Fixing quiz #%d — %s", quiz_id, feedback[:80])
        user = self._build_edit_user_prompt(topic, history, quiz_id, feedback)

        raw = await self._call_api_with_retry(user)
        quiz = self._try_parse_single_quiz(raw)

        if quiz is None:
            logger.warning("AI edit returned unparseable response, requesting reformat")
            fix_prompt = (
                "Tu respuesta anterior no era JSON válido. "
                "Aquí está tu respuesta:\n\n"
                f"{raw}\n\n"
                "Por favor, reformátala EXACTAMENTE como este ejemplo, "
                "sin texto adicional, sin markdown, sin ```:\n"
                '{"id":1,"question":"...","options":["A","B","C","D"],"correct":0}'
            )
            raw2 = await self._call_api_with_fix_prompt(user, fix_prompt)
            quiz = self._try_parse_single_quiz(raw2)

            if quiz is None:
                raise AIServiceError(
                    "La IA no pudo editar el quiz con formato válido. Intenta de nuevo.",
                    category="PARSE_ERROR",
                    status_code=502,
                )

        quiz.id = quiz_id
        return quiz

    # ── JSON parsing ────────────────────────────────────────

    def _try_parse_structured_response(self, text: str) -> Optional[dict]:
        """Parse {espanol: [...], ruso: [...]} response."""
        cleaned = re.sub(r"```(?:json)?\s*", "", text).strip().rstrip("`")

        try:
            data = json.loads(cleaned)
            if isinstance(data, dict) and ("espanol" in data or "ruso" in data):
                return self._parse_structured_dict(data)
        except (json.JSONDecodeError, KeyError, ValueError, TypeError):
            pass

        match = re.search(r"\{.*\}", text, re.DOTALL)
        if match:
            try:
                data = json.loads(match.group())
                if isinstance(data, dict) and ("espanol" in data or "ruso" in data):
                    return self._parse_structured_dict(data)
            except (json.JSONDecodeError, KeyError, ValueError, TypeError):
                pass

        return None

    def _parse_structured_dict(self, data: dict) -> dict:
        result = {}
        for key in ("espanol", "ruso"):
            items = data.get(key, [])
            if isinstance(items, list):
                result[key] = [Quiz.from_dict(item) for item in items if isinstance(item, dict)]
            else:
                result[key] = []
        return result

    def _try_parse_single_quiz(self, text: str) -> Optional[Quiz]:
        """Try to parse AI response into a single Quiz."""
        cleaned = re.sub(r"```(?:json)?\s*", "", text).strip().rstrip("`")

        try:
            data = json.loads(cleaned)
            if isinstance(data, dict):
                return Quiz.from_dict(data)
        except (json.JSONDecodeError, KeyError, ValueError, TypeError):
            pass

        match = re.search(r"\{.*\}", text, re.DOTALL)
        if match:
            try:
                data = json.loads(match.group())
                if isinstance(data, dict):
                    return Quiz.from_dict(data)
            except (json.JSONDecodeError, KeyError, ValueError, TypeError):
                pass

        return None

    # ── API calls ───────────────────────────────────────────

    async def _call_api_with_retry(self, user_prompt: str, agent: str = "quiz-generator") -> str:
        last_exception = None
        for attempt in range(self.max_retries + 1):
            try:
                if attempt > 0:
                    logger.info("[opencode] Retry attempt %d/%d — agent=%s", attempt, self.max_retries, agent)
                return await self._call_api(user_prompt, agent)
            except AIServiceError as e:
                last_exception = e
                # Retry on transient CLI failures (502) and timeouts (504)
                if e.status_code in (502, 504) and attempt < self.max_retries:
                    delay = self.base_delay * (2 ** attempt)
                    logger.warning("[opencode] CLI error (HTTP %d: %s), retrying in %ss (%d/%d)",
                                   e.status_code, e, delay, attempt + 1, self.max_retries)
                    await asyncio.sleep(delay)
                    continue
                raise
            except asyncio.TimeoutError as e:
                last_exception = e
                if attempt < self.max_retries:
                    delay = self.base_delay * (2 ** attempt)
                    logger.warning("[opencode] Timeout (retrying in %ss %d/%d)",
                                   delay, attempt + 1, self.max_retries)
                    await asyncio.sleep(delay)
                    continue
                raise
        if last_exception:
            raise last_exception
        raise AIServiceError("AI service failed after retries", category="EXTERNAL", status_code=502)

    async def _call_api(self, user_prompt: str, agent: str = "quiz-generator") -> str:
        """Call the opencode CLI, embedding agent instructions in the prompt."""
        import subprocess

        # Build environment with optional proxy
        import pathlib

        env = os.environ.copy()
        env["OPENCODE_CONFIG"] = str(pathlib.Path(__file__).resolve().parent.parent.parent / "agent" / "opencode.json")

        from bot.config import active_proxy_url
        if active_proxy_url:
            env["HTTP_PROXY"] = active_proxy_url
            env["HTTPS_PROXY"] = active_proxy_url

        # Embed agent instructions directly — remote API doesn't support --agent flag
        instructions = self._load_agent_instructions(agent)
        full_prompt = f"{instructions}\n\n---\n\n{user_prompt}" if instructions else user_prompt
        opencode_bin = self._resolve_opencode_bin()
        cmd = [opencode_bin, "run", full_prompt, "--format", "json"]

        logger.info("[opencode] CLI call started — agent=%s, prompt=%d chars", agent, len(full_prompt))
        t0 = time.monotonic()
        try:
            proc = await asyncio.create_subprocess_exec(
                *cmd,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                env=env,
                start_new_session=True,
            )
            stdout_bytes, stderr_bytes = await asyncio.wait_for(
                proc.communicate(), timeout=self.timeout
            )
        except asyncio.TimeoutError:
            elapsed = time.monotonic() - t0
            logger.error("[opencode] CLI timed out after %.1fs", elapsed)
            if proc and proc.returncode is None:
                try:
                    proc.kill()
                except OSError:
                    pass
                await proc.wait()
            raise AIServiceError(
                "AI service timed out",
                category="EXTERNAL",
                status_code=504,
            )

        stdout = stdout_bytes.decode("utf-8", errors="replace").strip()
        stderr = stderr_bytes.decode("utf-8", errors="replace").strip()

        elapsed = time.monotonic() - t0

        if proc.returncode != 0:
            logger.error("[opencode] CLI failed (exit %d) after %.1fs: %s", proc.returncode, elapsed, stderr[:200])
            raise AIServiceError(
                f"AI service CLI error (exit {proc.returncode}): {stderr[:200]}",
                category="EXTERNAL",
                status_code=502,
            )

        if not stdout:
            raise AIServiceError(
                "AI service returned empty response",
                category="EXTERNAL",
                status_code=502,
            )

        # Parse JSON event stream — look for the final text event
        assistant_content = self._extract_text_from_events(stdout)

        if not assistant_content:
            logger.error("No assistant message found in CLI output: %s", stdout[:500])
            raise AIServiceError(
                "AI service returned no assistant message",
                category="EXTERNAL",
                status_code=502,
            )

        logger.info("[opencode] CLI call completed — %d chars, %.1fs", len(assistant_content), elapsed)
        return assistant_content

    async def _call_api_with_fix_prompt(self, original_prompt: str, fix_prompt: str, agent: str = "quiz-generator") -> str:
        """Call CLI with feedback prompt, continuing the same session."""
        import subprocess

        # Build environment with optional proxy
        import pathlib

        env = os.environ.copy()
        env["OPENCODE_CONFIG"] = str(pathlib.Path(__file__).resolve().parent.parent.parent / "agent" / "opencode.json")

        from bot.config import active_proxy_url
        if active_proxy_url:
            env["HTTP_PROXY"] = active_proxy_url
            env["HTTPS_PROXY"] = active_proxy_url

        # Embed agent instructions directly — remote API doesn't support --agent flag
        instructions = self._load_agent_instructions(agent)
        full_prompt = f"{instructions}\n\n---\n\n{fix_prompt}" if instructions else fix_prompt
        opencode_bin = self._resolve_opencode_bin()
        cmd = [opencode_bin, "run", full_prompt, "--format", "json", "--continue"]

        logger.info("[opencode] Fix call started — agent=%s, prompt=%d chars", agent, len(full_prompt))
        t0 = time.monotonic()
        try:
            proc = await asyncio.create_subprocess_exec(
                *cmd,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                env=env,
                start_new_session=True,
            )
            stdout_bytes, stderr_bytes = await asyncio.wait_for(
                proc.communicate(), timeout=self.timeout
            )
        except asyncio.TimeoutError:
            elapsed = time.monotonic() - t0
            logger.error("[opencode] Fix call timed out after %.1fs", elapsed)
            if proc and proc.returncode is None:
                try:
                    proc.kill()
                except OSError:
                    pass
                await proc.wait()
            raise AIServiceError(
                "AI service timed out",
                category="EXTERNAL",
                status_code=504,
            )

        stdout = stdout_bytes.decode("utf-8", errors="replace").strip()
        stderr = stderr_bytes.decode("utf-8", errors="replace").strip()

        elapsed = time.monotonic() - t0

        if proc.returncode != 0:
            logger.error("[opencode] Fix call failed (exit %d) after %.1fs: %s", proc.returncode, elapsed, stderr[:200])
            raise AIServiceError(
                f"AI service CLI error (exit {proc.returncode}): {stderr[:200]}",
                category="EXTERNAL",
                status_code=502,
            )

        if not stdout:
            raise AIServiceError(
                "AI service returned empty response",
                category="EXTERNAL",
                status_code=502,
            )

        # Parse JSON event stream — look for the final text event
        assistant_content = self._extract_text_from_events(stdout)

        if not assistant_content:
            logger.error("No assistant message found in CLI output: %s", stdout[:500])
            raise AIServiceError(
                "AI service returned no assistant message",
                category="EXTERNAL",
                status_code=502,
            )

        logger.info("[opencode] Fix call completed — %d chars, %.1fs", len(assistant_content), elapsed)
        return assistant_content

    # ── opencode binary resolution ───────────────────────────

    @staticmethod
    def _resolve_opencode_bin() -> str:
        """Resolve the opencode executable path.

        On Windows, npm installs a ``.cmd`` shim that re-parses argv through
        ``cmd.exe``, which mangles shell metacharacters (``|``, ``&``, ``>``…)
        embedded in the prompt.  To avoid this we locate the real ``.exe``
        bundled by the ``opencode-ai`` npm package and invoke it directly.
        On POSIX systems ``shutil.which`` is sufficient.
        """
        if sys.platform != "win32":
            path = shutil.which("opencode")
            if path:
                return path
            raise FileNotFoundError("opencode not found on PATH — install it with 'npm i -g opencode-ai'")

        # Windows: look for the native .exe, skip the broken .cmd shim
        import pathlib

        def _search_dirs() -> list[pathlib.Path]:
            dirs: list[pathlib.Path] = []
            # npm global node_modules (most common)
            appdata = os.environ.get("APPDATA")
            if appdata:
                npm_global = pathlib.Path(appdata) / "npm" / "node_modules" / "opencode-ai" / "node_modules"
                for d in npm_global.glob("opencode-windows-*"):
                    dirs.append(d / "bin")
            # scoop
            user_profile = os.environ.get("USERPROFILE")
            if user_profile:
                dirs.append(pathlib.Path(user_profile) / "scoop" / "apps" / "opencode" / "current" / "bin")
            # chocolatey
                dirs.append(pathlib.Path(user_profile) / "AppData" / "Local" / "Programs" / "opencode")
            # opencode.ai installer
            local_app_data = os.environ.get("LOCALAPPDATA")
            if local_app_data:
                dirs.append(pathlib.Path(local_app_data) / "Programs" / "opencode")
            # common npm/pnpm/yarn global paths
            for env_var in ("NPM_CONFIG_PREFIX", "PNPM_HOME"):
                val = os.environ.get(env_var)
                if val:
                    dirs.append(pathlib.Path(val) / "node_modules" / "opencode-ai" / "node_modules" / "opencode-windows-x64" / "bin")
            return dirs

        for d in _search_dirs():
            exe = d / "opencode.exe"
            if exe.exists():
                return str(exe)

        # Fallback: shutil.which may still find the .cmd shim
        path = shutil.which("opencode")
        if path:
            return path

        raise FileNotFoundError(
            "opencode.exe not found — install with 'npm i -g opencode-ai' "
            "or 'scoop install opencode' or 'choco install opencode'"
        )

    # ── agent instruction loading ─────────────────────────────

    @staticmethod
    def _load_agent_instructions(agent: str) -> str:
        """Load markdown body from .opencode/agents/{agent}.md, stripping YAML frontmatter."""
        import pathlib
        md_path = pathlib.Path(__file__).resolve().parent.parent.parent / ".opencode" / "agents" / f"{agent}.md"
        try:
            raw = md_path.read_text(encoding="utf-8")
        except FileNotFoundError:
            logger.warning("Agent instruction file not found: %s", md_path)
            return ""
        # Strip YAML frontmatter (lines between --- delimiters)
        if raw.startswith("---"):
            end = raw.find("---", 3)
            if end != -1:
                raw = raw[end + 3:]
        return raw.strip()

    # ── event stream parsing ────────────────────────────────

    @staticmethod
    def _extract_text_from_events(stdout: str) -> str | None:
        """Extract assistant text from opencode JSONL event stream.

        opencode run --format json emits events like:
            {"type":"text","part":{"type":"text","text":"hello"}}
        Returns the concatenated text from all text events, or None.
        """
        parts: list[str] = []
        for line in stdout.splitlines():
            line = line.strip()
            if not line:
                continue
            try:
                event = json.loads(line)
            except json.JSONDecodeError:
                continue

            if event.get("type") == "text":
                part = event.get("part", {})
                text = part.get("text", "")
                if text and isinstance(text, str) and text.strip():
                    parts.append(text.strip())

        return "\n".join(parts) if parts else None

    # ── user prompt builders ─────────────────────────────────

    def _build_generate_user_prompt(
        self, topic: str, count_es: dict[str, int], count_ru: dict[str, int],
        level: str, dialect: str, examples: list[str] | None = None,
        forwarded_posts: list[str] | None = None,
    ) -> str:
        """Build user prompt with specific task parameters for quiz generation."""
        total_es = sum(count_es.values())
        total_ru = sum(count_ru.values())
        total = total_es + total_ru

        def _cat_list(counts: dict[str, int], lang: str) -> str:
            lines = []
            for key, n in counts.items():
                if n > 0:
                    lines.append(f"  - {n} de categoría '{key}'")
            return "\n".join(lines) if lines else f"  (ninguno en {lang})"

        es_list = _cat_list(count_es, "español")
        ru_list = _cat_list(count_ru, "ruso")

        # Build examples section (always present as baseline)
        examples_section = ""
        if examples:
            examples_text = "\n".join(f"  - {e}" for e in examples)
            examples_section = (
                f"\nORACIONES DEL POST ORIGINAL — ESTA ES LA BASE PRINCIPAL:\n"
                f"{examples_text}\n\n"
                f"REGLA CRÍTICA: El 60% de los quizzes DEBE venir de estas oraciones.\n"
                f"Estas oraciones son el material original del estudiante.\n"
                f"Modifícalas, extrae vocabulario, crea vacíos, pregunta sobre su significado.\n"
                f"El 40% restante pueden ser preguntas nuevas que complementen el tema.\n"
            )

        # Build multi-post ADDITIONAL context (added on top of baseline when 2+ posts)
        multi_post_addition = ""
        if forwarded_posts and len(forwarded_posts) > 1:
            posts_text = "\n\n---\n\n".join(forwarded_posts)
            multi_post_addition = (
                f"\n\n{'='*60}\n"
                f"QUIZ SEMANAL BASADO EN MÚLTIPLES POSTS\n"
                f"{'='*60}\n\n"
                f"El usuario reenvió {len(forwarded_posts)} posts de canales de español.\n"
                f"Este quiz es parte de una actividad SEMANAL de aprendizaje.\n\n"
                f"POSTS ORIGINALES:\n{posts_text}\n\n"
                f"INSTRUCCIONES PARA QUIZ SEMANAL:\n"
                f"- Crea quizzes que cubran el TEMA GENERAL que unifica todos los posts\n"
                f"- Distribuye los quizzes entre los diferentes aspectos de los posts\n"
                f"- Mantén coherencia temática entre todos los quizzes\n"
                f"- El 60% de los quizzes DEBE venir de las oraciones de ESTOS posts\n"
                f"- El 40% restante pueden ser preguntas complementarias sobre el tema\n"
                f"- El quiz semanal integra múltiples fuentes para cobertura temática completa\n"
            )

        return (
            f"Crea quizzes sobre: {topic}\n\n"
            f"Debes generar EXACTAMENTE {total} quizzes:\n\n"
            f"En ESPAÑOL ({total_es}):\n{es_list}\n\n"
            f"En RUSO ({total_ru}):\n{ru_list}\n\n"
            f"Nivel: {level}\n"
            f"Dialecto: {Dialect.from_name(dialect).prompt_text()}\n"
            f"{examples_section}"
            f"{multi_post_addition}"
        )

    def _build_topic_user_prompt(self, text: str, is_multi_post: bool, multi_post_context: str) -> str:
        """Build user prompt for topic determination."""
        dialect_names = ", ".join(Dialect.valid_names())
        dialect_details = "\n".join(f"  - {d.display_name}: {d.description[:80]}..." for d in Dialect)
        return (
            "Analiza el siguiente texto y determina si contiene material para aprender español.\n"
            "El texto fue reenviado por un estudiante de español.\n\n"
            "Si el texto contiene vocabulario, gramática, expresiones o contenido en español "
            "(aunque sea parcialmente), devuelve un tema real. SOLO devuelve NO_TOPIC si el "
            "texto NO contiene NADA relacionado con español.\n\n"
            "Responde SOLO con JSON válido (sin markdown, sin texto adicional):\n"
            '{"topic": "tema detectado", "examples": ["oración 1", "oración 2"], '
            '"level": "A1", "dialect": "Castellano"}\n\n'
            "Niveles válidos: A1, A2, B1, B2, C1, C2\n"
            f"Dialectos válidos: {dialect_names}\n\n"
            f"Descripción de dialectos:\n{dialect_details}\n\n"
            f"TEXTO:\n{text}"
            f"{multi_post_context}"
        )

    def _build_category_counts_user_prompt(
        self, topic: str, examples: list[str],
        count_es: dict[str, int], count_ru: dict[str, int],
        level: str, dialect: str,
    ) -> str:
        """Build user prompt for category count determination."""
        examples_text = "\n".join(f"  - {e}" for e in examples[:20]) if examples else "(sin ejemplos)"
        return (
            "Analiza el tema y sugiere cuántos quizzes crear por categoría e idioma.\n\n"
            "Responde SOLO con JSON válido (sin markdown, sin texto adicional):\n"
            '{"espanol": {"fill_blank": 2, "meaning": 1, "synonyms": 1, "slang": 0}, '
            '"ruso": {"fill_blank": 1, "meaning": 2, "synonyms": 0, "slang": 1}}\n\n'
            "Categorías válidas: fill_blank, meaning, synonyms, slang\n"
            "Cada categoría debe tener un valor >= 0.\n"
            "El total de quizzes (espanol + ruso) debe ser entre 4 y 8.\n\n"
            f"Tema: {topic}\n"
            f"Nivel: {level}\n"
            f"Dialecto: {Dialect.from_name(dialect).prompt_text()}\n\n"
            f"Oraciones de ejemplo:\n{examples_text}\n\n"
            f"Cantidades actuales:\n"
            f"  Español: {count_es}\n"
            f"  Ruso: {count_ru}"
        )

    def _build_review_user_prompt(self, quizzes_data: list[dict], topic: str, level: str, dialect: str) -> str:
        """Build user prompt for quiz review."""
        return (
            f"Tema: {topic} | Nivel: {level} | Dialecto: {Dialect.from_name(dialect).display_name}\n"
            f"Descripción del dialecto: {Dialect.from_name(dialect).description}\n\n"
            f"Quizzes a revisar:\n{json.dumps(quizzes_data, ensure_ascii=False, indent=2)}"
        )

    def _build_edit_user_prompt(
        self, topic: str, history: list[dict], quiz_id: int, feedback: str
    ) -> str:
        """Build user prompt for quiz editing."""
        history_text = json.dumps(history, ensure_ascii=False, indent=2)
        return (
            f"Tema: {topic}\n\n"
            f"Quizzes actuales:\n{history_text}\n\n"
            f"Quiz a editar: #{quiz_id}\n\n"
            f"Feedback del usuario: {feedback}\n\n"
            f"Edita SOLO el quiz #{quiz_id} según el feedback. "
            "Devuelve SOLO el quiz editado en formato JSON."
        )