import asyncio
import httpx
import json
import logging
import re
from dataclasses import dataclass, asdict
from typing import Optional

logger = logging.getLogger(__name__)


@dataclass
class Quiz:
    """Structured quiz generated by AI."""
    id: int
    question: str
    options: list[str]
    correct_index: int
    category: str = ""

    @property
    def correct_option(self) -> str:
        return self.options[self.correct_index]

    def to_dict(self) -> dict:
        return asdict(self)

    @classmethod
    def from_dict(cls, data: dict) -> "Quiz":
        correct = data.get("correct", data.get("correct_index", 0))
        return cls(
            id=int(data.get("id", 0)),
            question=str(data["question"]).strip(),
            options=[str(o).strip() for o in data["options"]],
            correct_index=int(correct),
            category=str(data.get("category", "")),
        )


@dataclass
class AutoDetected:
    """Auto-detected settings from a forwarded message."""
    topic: str
    examples: list[str]
    level: str  # A1-C2
    dialect: str  # Castellano, Mexicano, Argentino


class AIServiceError(Exception):
    def __init__(self, message: str, category: str = "EXTERNAL", status_code: int = 500):
        super().__init__(message)
        self.category = category
        self.status_code = status_code


class AIService:
    def __init__(self):
        self.api_url = "https://opencode.ai/zen/v1/chat/completions"
        self.model = "big-pickle"
        self.timeout = 90.0
        self.max_retries = 3
        self.base_delay = 1.0

    # ── public ──────────────────────────────────────────────

    async def generate_quizzes(
        self, topic: str, count_es: dict[str, int], count_ru: dict[str, int],
        level: str, dialect: str, examples: list[str] | None = None,
        forwarded_posts: list[str] | None = None,
    ) -> list[Quiz]:
        """
        Generate quizzes with per-category counts.
        count_es = {"fill_blank": 2, "meaning": 1, "synonyms": 0, "slang": 1}
        count_ru = {"fill_blank": 1, "meaning": 2, "synonyms": 1, "slang": 0}
        examples = optional list of example sentences from the original post
        forwarded_posts = optional list of forwarded post texts (for multi-post workflow)
        """
        total_es = sum(count_es.values())
        total_ru = sum(count_ru.values())

        system = self._system_prompt_generate(count_es, count_ru, level, dialect, examples, forwarded_posts)
        user = f"Crea quizzes sobre: {topic}"

        raw = await self._call_api_with_retry(system, user)
        result = self._try_parse_structured_response(raw)

        if result is None:
            logger.warning("AI returned unparseable response, requesting reformat")
            fix_prompt = (
                "Tu respuesta anterior no era JSON válido. "
                "Aquí está tu respuesta:\n\n"
                f"{raw}\n\n"
                "Por favor, reformátala EXACTAMENTE así, sin texto adicional, sin markdown, sin ```:\n"
                '{"espanol":[{"id":1,"category":"fill_blank","question":"...","options":["A","B","C","D"],"correct":0}],'
                '"ruso":[{"id":1,"category":"meaning","question":"...","options":["A","B","C","D"],"correct":0}]}'
            )
            raw2 = await self._call_api_with_retry(system, fix_prompt)
            result = self._try_parse_structured_response(raw2)

            if result is None:
                raise AIServiceError(
                    "La IA no pudo generar quizzes con formato válido. Intenta de nuevo.",
                    category="PARSE_ERROR",
                    status_code=502,
                )

        espanol_quizzes = result.get("espanol", [])
        ruso_quizzes = result.get("ruso", [])

        # Enforce totals
        espanol_quizzes = espanol_quizzes[:total_es]
        ruso_quizzes = ruso_quizzes[:total_ru]

        # Assign sequential ids
        all_quizzes = espanol_quizzes + ruso_quizzes
        for i, q in enumerate(all_quizzes):
            q.id = i + 1

        return all_quizzes

    async def determine_topic(self, text: str, is_multi_post: bool = False) -> AutoDetected:
        """Extract topic, examples, level, and dialect from a forwarded message or multiple posts."""
        multi_post_context = ""
        if is_multi_post:
            multi_post_context = (
                "\n\nCONTEXTO IMPORTANTE: Estos posts son parte de un quiz SEMANAL.\n"
                "El usuario reenvió múltiples posts de canales de español para crear un quiz.\n"
                "Determina un tema que unifique TODOS los posts.\n"
            )

        system = (
            "Eres un experto en enseñanza de español para rusohablantes.\n"
            "Recibes el texto de un mensaje reenviado de un canal de español.\n"
            "Tu tarea: determinar el TEMA, extraer oraciones, nivel CEFR y dialecto.\n\n"
            "REGLAS:\n"
            "- Responde SOLO con JSON válido, sin texto adicional\n"
            "- El JSON tiene esta forma:\n"
            '  {"topic":"...","examples":["..."],"level":"B1","dialect":"Castellano"}\n'
            "- 'topic' = tema conciso (2-5 palabras)\n"
            "- 'examples' = TODAS las oraciones/frases del mensaje que contengan español.\n"
            "  Extrae CADA oración completa. No omitas ninguna.\n"
            "  Son la BASE para crear los quizzes, necesitamos todas.\n"
            "- 'level' = nivel CEFR aproximado del contenido (A1, A2, B1, B2, C1, C2).\n"
            "  Analiza la complejidad gramatical y vocabulario para determinarlo.\n"
            "- 'dialect' = dialecto detectado del contenido:\n"
            "  - 'Castellano' (por defecto si no se detecta otro)\n"
            "  - 'Mexicano' (si usa vocabulario/gramática de México)\n"
            "  - 'Argentino' (si usa vocabulario/gramática de Argentina)\n"
            "- Si el texto no contiene material de español:\n"
            '  {"topic":"NO_TOPIC","examples":[],"level":"A1","dialect":"Castellano"}'
            f"{multi_post_context}"
        )
        raw = await self._call_api_with_retry(system, text)

        # Parse JSON
        cleaned = re.sub(r"```(?:json)?\s*", "", raw).strip().rstrip("`")
        try:
            data = json.loads(cleaned)
            return self._parse_auto_detected(data)
        except (json.JSONDecodeError, KeyError, ValueError, TypeError):
            pass

        # Try regex fallback
        match = re.search(r"\{.*\}", raw, re.DOTALL)
        if match:
            try:
                data = json.loads(match.group())
                return self._parse_auto_detected(data)
            except (json.JSONDecodeError, KeyError, ValueError, TypeError):
                pass

        # Last resort
        return AutoDetected(topic="NO_TOPIC", examples=[], level="A1", dialect="Castellano")

    def _parse_auto_detected(self, data: dict) -> AutoDetected:
        topic = str(data.get("topic", "NO_TOPIC")).strip()
        examples = [str(e).strip() for e in data.get("examples", []) if isinstance(e, str)]
        level = str(data.get("level", "A1")).strip().upper()
        dialect = str(data.get("dialect", "Castellano")).strip().capitalize()

        # Validate level
        if level not in ("A1", "A2", "B1", "B2", "C1", "C2"):
            level = "A1"
        # Validate dialect
        if dialect not in ("Castellano", "Mexicano", "Argentino"):
            dialect = "Castellano"

        return AutoDetected(topic=topic, examples=examples, level=level, dialect=dialect)

    async def determine_category_counts(
        self, topic: str, examples: list[str],
        count_es: dict[str, int], count_ru: dict[str, int],
        level: str, dialect: str,
    ) -> tuple[dict[str, int], dict[str, int]]:
        """
        Analyze the topic and examples to suggest category counts per language.
        Returns (counts_es, counts_ru) with values 0+ per category.
        The AI decides what makes sense given the content.
        """
        system = (
            "Eres un experto en crear quizzes de español para rusohablantes.\n"
            "Recibes un tema, oraciones de ejemplo, y las cantidades actuales por categoría.\n"
            "Tu tarea: sugerir las cantidades óptimas de quizzes por categoría e idioma.\n\n"
            "REGLAS:\n"
            "- Responde SOLO con JSON válido, sin texto adicional\n"
            "- El JSON tiene esta forma:\n"
            '  {"espanol":{"fill_blank":2,"meaning":1,"synonyms":1,"slang":0},'
            '"ruso":{"fill_blank":1,"meaning":2,"synonyms":0,"slang":1}}\n'
            "- Cada valor es un número entero >= 0 (sin máximo — elige la cantidad óptima)\n"
            "- El total por idioma debe ser al menos 1 (nunca 0 quizzes en un idioma)\n"
            "- Analiza las oraciones para decidir qué categorías encajan mejor:\n"
            "  - fill_blank: oraciones con vocabulario que se pueda ocultar\n"
            "  - meaning: expresiones con significado contextual\n"
            "  - synonyms: palabras que tengan sinónimos/antónimos claros\n"
            "  - slang: expresiones coloquiales o informales\n"
            "- Si el contenido no permite ciertas categorías, pon 0\n"
            "- Diversifica: no pongas todo en una sola categoría"
        )
        examples_text = "\n".join(f"  - {e}" for e in examples[:20]) if examples else "(sin ejemplos)"
        user = (
            f"Tema: {topic}\n"
            f"Nivel: {level} | Dialecto: {dialect}\n\n"
            f"Oraciones de ejemplo:\n{examples_text}\n\n"
            f"Cantidades actuales:\n"
            f"  Español: {count_es}\n"
            f"  Ruso: {count_ru}\n\n"
            "Sugerencias las cantidades óptimas de quizzes por categoría e idioma."
        )
        raw = await self._call_api_with_retry(system, user)

        # Parse JSON
        cleaned = re.sub(r"```(?:json)?\s*", "", raw).strip().rstrip("`")
        try:
            data = json.loads(cleaned)
            return self._parse_category_counts(data, count_es, count_ru)
        except (json.JSONDecodeError, KeyError, ValueError, TypeError):
            pass

        match = re.search(r"\{.*\}", raw, re.DOTALL)
        if match:
            try:
                data = json.loads(match.group())
                return self._parse_category_counts(data, count_es, count_ru)
            except (json.JSONDecodeError, KeyError, ValueError, TypeError):
                pass

        # Fallback: return original counts unchanged
        return count_es, count_ru

    @staticmethod
    def _parse_category_counts(
        data: dict, default_es: dict[str, int], default_ru: dict[str, int]
    ) -> tuple[dict[str, int], dict[str, int]]:
        raw_es = data.get("espanol", {})
        raw_ru = data.get("ruso", {})

        def _valid(raw: dict, defaults: dict[str, int]) -> dict[str, int]:
            out = {}
            for key in defaults:
                val = raw.get(key, defaults[key])
                val = max(0, int(val))  # no upper cap
                out[key] = val
            if sum(out.values()) < 1:
                # Ensure at least 1 total — set first category to 1
                first_key = list(out.keys())[0]
                out[first_key] = 1
            return out

        return _valid(raw_es, default_es), _valid(raw_ru, default_ru)

    async def review_quizzes(
        self, quizzes: list[Quiz], topic: str, level: str, dialect: str,
    ) -> list[dict]:
        """
        Review all quizzes for technical issues.
        Returns a list of issues: [{"id": 3, "issue": "...", "fix": {...}}, ...]
        Empty list = no issues found.
        """
        system = (
            "Eres un revisor experto de quizzes de español para rusohablantes.\n"
            "Recibes una lista de quizzes y debes encontrar ERRORES TÉCNICOS.\n\n"
            "ERRORES A DETECTAR:\n"
            "1. RESPUESTA CORRECTA MAL: el campo 'correct' apunta a la opción equivocada\n"
            "2. RESPUESTA EN LA PREGUNTA: la respuesta correcta aparece en el texto de la pregunta\n"
            "3. REPETICIÓN: dos quizzes usan la misma oración/pregunta casi idéntica\n"
            "4. OPCIONES SIMILARES DOS: dos opciones de respuesta son prácticamente lo mismo\n"
            "5. OPCIONES SIMILARES TRES+: tres o más opciones son muy parecidas\n"
            "6. CATEGORÍA MAL: la categoría no corresponde al tipo de pregunta\n"
            "7. PREGUNTA VACÍA O MAL: la pregunta no tiene sentido o está incompleta\n"
            "8. OPCIONES INSUFICIENTES: menos de 3 opciones válidas\n"
            "9. DUPLICADO EXACTO: dos quizzes tienen la misma pregunta\n\n"
            "NO DETECTES (eso es gusto del usuario):\n"
            "- Estilo o tono de la pregunta\n"
            "- Si el tema es interesante o no\n"
            "- Si el nivel de dificultad es adecuado\n\n"
            "REGLAS DE RESPUESTA:\n"
            "- Responde SOLO con JSON válido, sin texto adicional\n"
            "- Si NO hay errores: {\"issues\":[]}\n"
            "- Si HAY errores: {\"issues\":[{\"id\":3,\"issue\":\"...\",\"fix\":{\"question\":\"...\",\"options\":[...],\"correct\":0}}]}\n"
            "- 'id' = el id del quiz con problema\n"
            "- 'issue' = descripción breve del problema\n"
            "- 'fix' = la versión corregida del quiz completo (question, options, correct, category)\n"
            "- Si un quiz tiene múltiples problemas, incluye UN solo fix que los resuelva todos\n"
            "- NO corrijas el id ni la categoría del quiz, solo question, options y correct"
        )

        quizzes_data = [q.to_dict() for q in quizzes]
        user = (
            f"Tema: {topic} | Nivel: {level} | Dialecto: {dialect}\n\n"
            f"Quizzes a revisar:\n{json.dumps(quizzes_data, ensure_ascii=False, indent=2)}"
        )

        raw = await self._call_api_with_retry(system, user)

        # Parse JSON
        cleaned = re.sub(r"```(?:json)?\s*", "", raw).strip().rstrip("`")
        try:
            data = json.loads(cleaned)
            return data.get("issues", [])
        except (json.JSONDecodeError, KeyError, ValueError, TypeError):
            pass

        match = re.search(r"\{.*\}", raw, re.DOTALL)
        if match:
            try:
                data = json.loads(match.group())
                return data.get("issues", [])
            except (json.JSONDecodeError, KeyError, ValueError, TypeError):
                pass

        # If we can't parse the review, return empty (no issues) — don't block publishing
        logger.warning("AI review returned unparseable response, skipping review")
        return []

    async def edit_quiz(
        self, topic: str, history: list[dict], quiz_id: int, feedback: str
    ) -> Quiz:
        """Edit a single quiz (PATCH style). Returns only the modified quiz."""
        system = self._system_prompt_edit()
        user = self._edit_user_prompt(topic, history, quiz_id, feedback)

        raw = await self._call_api_with_retry(system, user)
        quiz = self._try_parse_single_quiz(raw)

        if quiz is None:
            logger.warning("AI edit returned unparseable response, requesting reformat")
            fix_prompt = (
                "Tu respuesta anterior no era JSON válido. "
                "Aquí está tu respuesta:\n\n"
                f"{raw}\n\n"
                "Por favor, reformátala EXACTAMENTE como este ejemplo, "
                "sin texto adicional, sin markdown, sin ```:\n"
                '{"id":1,"question":"...","options":["A","B","C","D"],"correct":0}'
            )
            raw2 = await self._call_api_with_retry(self._system_prompt_edit(), fix_prompt)
            quiz = self._try_parse_single_quiz(raw2)

            if quiz is None:
                raise AIServiceError(
                    "La IA no pudo editar el quiz con formato válido. Intenta de nuevo.",
                    category="PARSE_ERROR",
                    status_code=502,
                )

        quiz.id = quiz_id
        return quiz

    # ── JSON parsing ────────────────────────────────────────

    def _try_parse_structured_response(self, text: str) -> Optional[dict]:
        """Parse {espanol: [...], ruso: [...]} response."""
        cleaned = re.sub(r"```(?:json)?\s*", "", text).strip().rstrip("`")

        try:
            data = json.loads(cleaned)
            if isinstance(data, dict) and ("espanol" in data or "ruso" in data):
                return self._parse_structured_dict(data)
        except (json.JSONDecodeError, KeyError, ValueError, TypeError):
            pass

        match = re.search(r"\{.*\}", text, re.DOTALL)
        if match:
            try:
                data = json.loads(match.group())
                if isinstance(data, dict) and ("espanol" in data or "ruso" in data):
                    return self._parse_structured_dict(data)
            except (json.JSONDecodeError, KeyError, ValueError, TypeError):
                pass

        return None

    def _parse_structured_dict(self, data: dict) -> dict:
        result = {}
        for key in ("espanol", "ruso"):
            items = data.get(key, [])
            if isinstance(items, list):
                result[key] = [Quiz.from_dict(item) for item in items if isinstance(item, dict)]
            else:
                result[key] = []
        return result

    def _try_parse_single_quiz(self, text: str) -> Optional[Quiz]:
        """Try to parse AI response into a single Quiz."""
        cleaned = re.sub(r"```(?:json)?\s*", "", text).strip().rstrip("`")

        try:
            data = json.loads(cleaned)
            if isinstance(data, dict):
                return Quiz.from_dict(data)
        except (json.JSONDecodeError, KeyError, ValueError, TypeError):
            pass

        match = re.search(r"\{.*\}", text, re.DOTALL)
        if match:
            try:
                data = json.loads(match.group())
                if isinstance(data, dict):
                    return Quiz.from_dict(data)
            except (json.JSONDecodeError, KeyError, ValueError, TypeError):
                pass

        return None

    # ── API calls ───────────────────────────────────────────

    async def _call_api_with_retry(self, system_prompt: str, user_prompt: str) -> str:
        last_exception = None
        for attempt in range(self.max_retries + 1):
            try:
                return await self._call_api(system_prompt, user_prompt)
            except httpx.HTTPStatusError as e:
                last_exception = e
                if e.response.status_code == 429 and attempt < self.max_retries:
                    retry_after = e.response.headers.get("Retry-After")
                    delay = float(retry_after) if retry_after else self.base_delay * (2 ** attempt)
                    logger.warning("Rate limited (429), retrying in %ss (%d/%d)",
                                   delay, attempt + 1, self.max_retries)
                    await asyncio.sleep(delay)
                    continue
                raise
            except (httpx.TimeoutException, httpx.NetworkError) as e:
                last_exception = e
                if attempt < self.max_retries:
                    delay = self.base_delay * (2 ** attempt)
                    logger.warning("Transient error (%s: %s), retrying in %ss (%d/%d)",
                                   type(e).__name__, e, delay, attempt + 1, self.max_retries)
                    await asyncio.sleep(delay)
                    continue
                raise
        if last_exception:
            raise last_exception
        raise AIServiceError("AI service failed after retries", category="EXTERNAL", status_code=502)

    async def _call_api(self, system_prompt: str, user_prompt: str) -> str:
        headers = {
            "Content-Type": "application/json",
            "User-Agent": "opencode/1.18.15",
        }
        payload = {
            "model": self.model,
            "messages": [
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_prompt},
            ],
            "temperature": 0.7,
        }

        from bot.config import active_proxy_url
        async with httpx.AsyncClient(timeout=self.timeout, proxy=active_proxy_url) as client:
            resp = await client.post(self.api_url, headers=headers, json=payload)
            resp.raise_for_status()
            data = resp.json()

            if "choices" not in data or not data["choices"]:
                raise ValueError("Invalid response: missing 'choices'")
            content = data["choices"][0].get("message", {}).get("content", "")
            if not isinstance(content, str) or not content.strip():
                raise ValueError("Invalid response: empty content")
            return content.strip()

    # ── prompts ─────────────────────────────────────────────

    def _system_prompt_generate(
        self, count_es: dict[str, int], count_ru: dict[str, int], level: str,
        dialect: str, examples: list[str] | None = None,
        forwarded_posts: list[str] | None = None,
    ) -> str:
        total_es = sum(count_es.values())
        total_ru = sum(count_ru.values())
        total = total_es + total_ru

        def _cat_list(counts: dict[str, int], lang: str) -> str:
            lines = []
            for key, n in counts.items():
                if n > 0:
                    lines.append(f"  - {n} de categoría '{key}'")
            return "\n".join(lines) if lines else f"  (ninguno en {lang})"

        es_list = _cat_list(count_es, "español")
        ru_list = _cat_list(count_ru, "ruso")

        # Build examples section (always present as baseline)
        examples_section = ""
        if examples:
            examples_text = "\n".join(f"  - {e}" for e in examples)
            examples_section = (
                f"\nORACIONES DEL POST ORIGINAL — ESTA ES LA BASE PRINCIPAL:\n"
                f"{examples_text}\n\n"
                f"REGLA CRÍTICA: El 60% de los quizzes DEBE venir de estas oraciones.\n"
                f"Estas oraciones son el material original del estudiante.\n"
                f"Modifícalas, extrae vocabulario, crea vacíos, pregunta sobre su significado.\n"
                f"El 40% restante pueden ser preguntas nuevas que complementen el tema.\n"
            )

        # Build multi-post ADDITIONAL context (added on top of baseline when 2+ posts)
        multi_post_addition = ""
        if forwarded_posts and len(forwarded_posts) > 1:
            posts_text = "\n\n---\n\n".join(forwarded_posts)
            multi_post_addition = (
                f"\n\n{'='*60}\n"
                f"QUIZ SEMANAL BASADO EN MÚLTIPLES POSTS\n"
                f"{'='*60}\n\n"
                f"El usuario reenvió {len(forwarded_posts)} posts de canales de español.\n"
                f"Este quiz es parte de una actividad SEMANAL de aprendizaje.\n\n"
                f"POSTS ORIGINALES:\n{posts_text}\n\n"
                f"INSTRUCCIONES PARA QUIZ SEMANAL:\n"
                f"- Crea quizzes que cubran el TEMA GENERAL que unifica todos los posts\n"
                f"- Distribuye los quizzes entre los diferentes aspectos de los posts\n"
                f"- Mantén coherencia temática entre todos los quizzes\n"
                f"- El 60% de los quizzes DEBE venir de las oraciones de ESTOS posts\n"
                f"- El 40% restante pueden ser preguntas complementarias sobre el tema\n"
                f"- El quiz semanal integra múltiples fuentes para cobertura temática completa\n"
            )

        return (
            "Eres un experto en crear quizzes de español para estudiantes rusohablantes.\n\n"
            f"Categorías de quiz:\n"
            "  - fill_blank: Cumplimentar espacios en blanco (completar la palabra correcta)\n"
            "  - meaning: Dar respuesta al significado de una expresión\n"
            "  - synonyms: Opción de sinónimos / antónimos\n"
            "  - slang: Opción de EDUCADO / Slang\n\n"
            f"Debes generar EXACTAMENTE {total} quizzes:\n\n"
            f"En ESPAÑOL ({total_es}):\n{es_list}\n\n"
            f"En RUSO ({total_ru}):\n{ru_list}\n\n"
            f"Nivel: {level}\n"
            f"Dialecto: {dialect}\n"
            f"{examples_section}"
            f"{multi_post_addition}\n"
            "REGLAS:\n"
            "- Responde SOLO con un JSON válido, sin texto adicional\n"
            "- El JSON tiene esta forma exacta:\n"
            '  {"espanol":[...],"ruso":[...]}\n'
            "- Cada quiz dentro de los arrays tiene esta forma:\n"
            '  {"id":1,"category":"fill_blank","question":"...","options":["A","B","C","D"],"correct":0}\n'
            "- 'id' = número secuencial empezando en 1 DENTRO de cada array\n"
            "- 'category' = clave de categoría: fill_blank, meaning, synonyms, slang\n"
            "- 'question' = la pregunta clara y concisa\n"
            "- 'options' = entre 3 y 4 opciones de respuesta\n"
            "- 'correct' = índice (0-based) de la respuesta correcta\n"
            "- Las preguntas en español deben ser 100% en español\n"
            "- Las preguntas en ruso deben ser 100% en ruso\n"
            "- Las opciones de respuesta pueden estar en el idioma que corresponda\n"
            f"- Las preguntas deben ser apropiadas para nivel {level}\n"
            f"- Dialecto {dialect}: usa sus particularidades de gramática y vocabulario, "
            "PERO el quiz se centra en el TEMA, no en el dialecto\n"
            "- DIFICULTAD CRECIENTE dentro de cada idioma\n"
            f"- DEBES generar exactamente las cantidades especificadas por categoría\n\n"
            "REGLA FUNDAMENTAL — INDEPENDENCIA TOTAL ENTRE IDIOMAS:\n"
            "Los quizzes en español y en ruso son DOS MUNDOS COMPLETAMENTE SEPARADOS.\n"
            "NO son traducciones el uno del otro. NO comparten ejemplos, microtemas,\n"
            "ni contenido. Si la oración X se usó en un quiz en español, NO puede\n"
            "aparecer en ningún quiz en ruso, y viceversa.\n"
            "Cada idioma tiene su propia pool de ejemplos, su propio ángulo,\n"
            "sus propias oraciones de ejemplo. Piensa en ellos como dos reinos\n"
            "distintos de un mismo tema — comparten la frontera, no los ciudadanos.\n"
            "El 60% de oraciones originales se divide: unas para español, otras para ruso.\n"
            "Nunca las dupliques entre idiomas."
        )

    def _system_prompt_edit(self) -> str:
        return (
            "Eres un experto en crear quizzes de español para estudiantes.\n"
            "Recibes el historial de quizzes y un feedback para EDITAR uno solo.\n\n"
            "REGLAS:\n"
            "- Responde SOLO con JSON válido de UN SOLO quiz, sin texto adicional\n"
            "- El JSON tiene esta forma:\n"
            '  {"id":1,"question":"...","options":["A","B","C","D"],"correct":0}\n'
            "- 'id' = el mismo id del quiz que estás editando\n"
            "- SOLO devuelve el quiz editado, NO los demás\n"
            "- Mantén el idioma del quiz (español o ruso)\n"
            "- Mantén la coherencia con los otros quizzes del historial\n"
            "- Aplica el feedback del usuario\n"
            "- Todo en el idioma original del quiz"
        )

    def _edit_user_prompt(
        self, topic: str, history: list[dict], quiz_id: int, feedback: str
    ) -> str:
        history_text = json.dumps(history, ensure_ascii=False, indent=2)
        return (
            f"Tema: {topic}\n\n"
            f"Quizzes actuales:\n{history_text}\n\n"
            f"Quiz a editar: #{quiz_id}\n\n"
            f"Feedback del usuario: {feedback}\n\n"
            f"Edita SOLO el quiz #{quiz_id} según el feedback. "
            "Devuelve SOLO el quiz editado en formato JSON."
        )
