import asyncio
import httpx
import json
import logging
import re
from dataclasses import dataclass, asdict
from typing import Optional

logger = logging.getLogger(__name__)


@dataclass
class Quiz:
    """Structured quiz generated by AI."""
    id: int
    question: str
    options: list[str]
    correct_index: int

    @property
    def correct_option(self) -> str:
        return self.options[self.correct_index]

    def to_dict(self) -> dict:
        return asdict(self)

    @classmethod
    def from_dict(cls, data: dict) -> "Quiz":
        # AI returns "correct", internal uses "correct_index"
        correct = data.get("correct", data.get("correct_index", 0))
        return cls(
            id=int(data.get("id", 0)),
            question=str(data["question"]).strip(),
            options=[str(o).strip() for o in data["options"]],
            correct_index=int(correct),
        )


class AIServiceError(Exception):
    def __init__(self, message: str, category: str = "EXTERNAL", status_code: int = 500):
        super().__init__(message)
        self.category = category
        self.status_code = status_code


class AIService:
    def __init__(self):
        self.api_url = "https://opencode.ai/zen/v1/chat/completions"
        self.model = "big-pickle"
        self.timeout = 90.0
        self.max_retries = 3
        self.base_delay = 1.0

    # ── public ──────────────────────────────────────────────

    async def generate_quizzes(self, topic: str, count: int, level: str) -> list[Quiz]:
        """Generate N quizzes from a topic. Difficulty increases from 1 to N."""
        system = self._system_prompt_generate(count, level)
        user = f"Crea {count} quizzes sobre: {topic}"

        raw = await self._call_api_with_retry(system, user)
        quizzes = self._try_parse_quiz_array(raw)

        if quizzes is None:
            logger.warning("AI returned unparseable response, requesting reformat")
            fix_prompt = (
                "Tu respuesta anterior no era JSON válido. "
                "Aquí está tu respuesta:\n\n"
                f"{raw}\n\n"
                "Por favor, reformátala como un ARRAY JSON exactamente así, "
                "sin texto adicional, sin markdown, sin ```:\n"
                '[{"id":1,"question":"...","options":["A","B","C","D"],"correct":0},'
                '{"id":2,"question":"...","options":["A","B","C","D"],"correct":1}]'
            )
            raw2 = await self._call_api_with_retry(self._system_prompt_generate(count, level), fix_prompt)
            quizzes = self._try_parse_quiz_array(raw2)

            if quizzes is None:
                raise AIServiceError(
                    "La IA no pudo generar quizzes con formato válido. Intenta de nuevo.",
                    category="PARSE_ERROR",
                    status_code=502,
                )

        # Ensure correct count and sequential ids
        quizzes = quizzes[:count]
        for i, q in enumerate(quizzes):
            q.id = i + 1

        return quizzes

    async def edit_quiz(
        self, topic: str, history: list[dict], quiz_id: int, feedback: str
    ) -> Quiz:
        """Edit a single quiz (PATCH style). Returns only the modified quiz."""
        system = self._system_prompt_edit()
        user = self._edit_user_prompt(topic, history, quiz_id, feedback)

        raw = await self._call_api_with_retry(system, user)
        quiz = self._try_parse_single_quiz(raw)

        if quiz is None:
            logger.warning("AI edit returned unparseable response, requesting reformat")
            fix_prompt = (
                "Tu respuesta anterior no era JSON válido. "
                "Aquí está tu respuesta:\n\n"
                f"{raw}\n\n"
                "Por favor, reformátala EXACTAMENTE como este ejemplo, "
                "sin texto adicional, sin markdown, sin ```:\n"
                '{"id":1,"question":"...","options":["A","B","C","D"],"correct":0}'
            )
            raw2 = await self._call_api_with_retry(self._system_prompt_edit(), fix_prompt)
            quiz = self._try_parse_single_quiz(raw2)

            if quiz is None:
                raise AIServiceError(
                    "La IA no pudo editar el quiz con formato válido. Intenta de nuevo.",
                    category="PARSE_ERROR",
                    status_code=502,
                )

        quiz.id = quiz_id
        return quiz

    # ── JSON parsing ────────────────────────────────────────

    def _try_parse_quiz_array(self, text: str) -> Optional[list[Quiz]]:
        """Try to parse AI response into a list of Quizzes."""
        cleaned = re.sub(r"```(?:json)?\s*", "", text).strip().rstrip("`")

        # Direct parse
        try:
            data = json.loads(cleaned)
            if isinstance(data, list):
                return [Quiz.from_dict(item) for item in data]
        except (json.JSONDecodeError, KeyError, ValueError, TypeError):
            pass

        # Extract JSON array from surrounding text
        match = re.search(r"\[.*\]", text, re.DOTALL)
        if match:
            try:
                data = json.loads(match.group())
                if isinstance(data, list):
                    return [Quiz.from_dict(item) for item in data]
            except (json.JSONDecodeError, KeyError, ValueError, TypeError):
                pass

        return None

    def _try_parse_single_quiz(self, text: str) -> Optional[Quiz]:
        """Try to parse AI response into a single Quiz."""
        cleaned = re.sub(r"```(?:json)?\s*", "", text).strip().rstrip("`")

        try:
            data = json.loads(cleaned)
            if isinstance(data, dict):
                return Quiz.from_dict(data)
        except (json.JSONDecodeError, KeyError, ValueError, TypeError):
            pass

        match = re.search(r"\{.*\}", text, re.DOTALL)
        if match:
            try:
                data = json.loads(match.group())
                if isinstance(data, dict):
                    return Quiz.from_dict(data)
            except (json.JSONDecodeError, KeyError, ValueError, TypeError):
                pass

        return None

    # ── API calls ───────────────────────────────────────────

    async def _call_api_with_retry(self, system_prompt: str, user_prompt: str) -> str:
        last_exception = None
        for attempt in range(self.max_retries + 1):
            try:
                return await self._call_api(system_prompt, user_prompt)
            except httpx.HTTPStatusError as e:
                last_exception = e
                if e.response.status_code == 429 and attempt < self.max_retries:
                    retry_after = e.response.headers.get("Retry-After")
                    delay = float(retry_after) if retry_after else self.base_delay * (2 ** attempt)
                    logger.info("Rate limited, retrying in %ss (%d/%d)", delay, attempt + 1, self.max_retries)
                    await asyncio.sleep(delay)
                    continue
                raise
            except (httpx.TimeoutException, httpx.NetworkError) as e:
                last_exception = e
                if attempt < self.max_retries:
                    delay = self.base_delay * (2 ** attempt)
                    logger.info("Transient error, retrying in %ss (%d/%d)", delay, attempt + 1, self.max_retries)
                    await asyncio.sleep(delay)
                    continue
                raise
        if last_exception:
            raise last_exception
        raise AIServiceError("AI service failed after retries", category="EXTERNAL", status_code=502)

    async def _call_api(self, system_prompt: str, user_prompt: str) -> str:
        headers = {
            "Content-Type": "application/json",
            "User-Agent": "opencode/1.18.15",
        }
        payload = {
            "model": self.model,
            "messages": [
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_prompt},
            ],
            "temperature": 0.7,
        }

        async with httpx.AsyncClient(timeout=self.timeout) as client:
            resp = await client.post(self.api_url, headers=headers, json=payload)
            resp.raise_for_status()
            data = resp.json()

            if "choices" not in data or not data["choices"]:
                raise ValueError("Invalid response: missing 'choices'")
            content = data["choices"][0].get("message", {}).get("content", "")
            if not isinstance(content, str) or not content.strip():
                raise ValueError("Invalid response: empty content")
            return content.strip()

    # ── prompts ─────────────────────────────────────────────

    def _system_prompt_generate(self, count: int, level: str) -> str:
        return (
            "Eres un experto en crear quizzes de español para estudiantes.\n\n"
            f"Debes generar EXACTAMENTE {count} quizzes de opción múltiple para nivel {level}.\n\n"
            "REGLAS:\n"
            "- Responde SOLO con un array JSON válido, sin texto adicional\n"
            f"- El array debe tener exactamente {count} objetos\n"
            "- Cada objeto tiene esta forma:\n"
            '  {"id":1,"question":"...","options":["A","B","C","D"],"correct":0}\n'
            "- 'id' = número secuencial empezando en 1\n"
            "- 'question' = la pregunta clara y concisa, SIN prefijo de nivel\n"
            "- 'options' = entre 3 y 4 opciones de respuesta\n"
            "- 'correct' = índice (0-based) de la respuesta correcta\n"
            "- Todo en español\n"
            f"- Las preguntas deben ser apropiadas para nivel {level}\n"
            "- Las opciones incorrectas deben ser creíbles (errores comunes)\n"
            "- DIFICULTAD CRECIENTE: el quiz 1 debe ser el más fácil, "
            f"el quiz {count} debe ser el más difícil\n"
            "- Varía los tipos de pregunta (completar, seleccionar, conjugación, etc.)"
        )

    def _system_prompt_edit(self) -> str:
        return (
            "Eres un experto en crear quizzes de español para estudiantes.\n"
            "Recibes el historial de quizzes y un feedback para EDITAR uno solo.\n\n"
            "REGLAS:\n"
            "- Responde SOLO con JSON válido de UN SOLO quiz, sin texto adicional\n"
            "- El JSON tiene esta forma:\n"
            '  {"id":1,"question":"...","options":["A","B","C","D"],"correct":0}\n'
            "- 'id' = el mismo id del quiz que estás editando\n"
            "- SOLO devuelve el quiz editado, NO los demás\n"
            "- Mantén la coherencia con los otros quizzes del historial\n"
            "- Aplica el feedback del usuario\n"
            "- Todo en español"
        )

    def _edit_user_prompt(
        self, topic: str, history: list[dict], quiz_id: int, feedback: str
    ) -> str:
        history_text = json.dumps(history, ensure_ascii=False, indent=2)
        return (
            f"Tema: {topic}\n\n"
            f"Quizzes actuales:\n{history_text}\n\n"
            f"Quiz a editar: #{quiz_id}\n\n"
            f"Feedback del usuario: {feedback}\n\n"
            f"Edita SOLO el quiz #{quiz_id} según el feedback. "
            "Devuelve SOLO el quiz editado en formato JSON."
        )
